hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs_piratenets/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working direcotry unchaned
    config:
      override_dirname:
        exclude_keys:
          - TRAIN.checkpoint_path
          - TRAIN.pretrained_model_path
          - EVAL.pretrained_model_path
          - INFER.pretrained_model_path
          - mode
          - output_dir
          - log_freq

  callbacks:
    init_callback:
      _target_: ppsci.utils.callbacks.InitCallback
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# general settings
mode: train # running mode: train/eval
seed: 42
output_dir: ${hydra:run.dir}
log_freq: 100
use_tbd: false
use_vdl: false
use_wandb: false
wandb_config: null
device: "gpu"
to_static: false
use_amp: false
amp_level: "O1"

DATA_PATH: "./dataset/allen_cahn.mat"

# model settings
MODEL:
  input_keys: ["t", "x"]
  output_keys: ["u",]
  num_layers: 9
  hidden_size: 256
  alpha: 0
  mu: 1.0 # random weight 
  sigma: 0.1
  activation: "Tanh"
  periods:
    x: ["2.0", false] # [period, trainable]
  fourier:
    dim: 256
    scale: 2.0

# training settings
TRAIN:
  epochs: 300
  iters_per_epoch: 1000
  save_freq: 10
  eval_during_train: true
  eval_freq: 10
  lr_scheduler:
    epochs: ${TRAIN.epochs}
    iters_per_epoch: ${TRAIN.iters_per_epoch}
    learning_rate: 1.0e-3
    gamma: 0.9
    decay_steps: 5000
    by_epoch: false
  batch_size: 8192
  pretrained_model_path: null
  checkpoint_path: null
  update_freq: 1
  start_eval_epoch: 1
  causal:
    n_chunks: 32
    tol: 1.0
  # grad_norm:
  #   update_freq: 1000
  #   momentum: 0.9
  ntk:
    update_freq: 1000

# evaluation settings
EVAL:
  pretrained_model_path: null
  eval_with_no_grad: true
  compute_metric_by_batch: false
  batch_size: 4096

# inference settings
INFER:
  pretrained_model_path: null
  export_path: ./inference/allen_cahn
  pdmodel_path: ${INFER.export_path}.pdmodel
  pdiparams_path: ${INFER.export_path}.pdiparams
  onnx_path: ${INFER.export_path}.onnx
  device: gpu
  engine: native
  precision: fp32
  ir_optim: true
  min_subgraph_size: 5
  gpu_mem: 2000
  gpu_id: 0
  max_batch_size: 1024
  num_cpu_threads: 10
  batch_size: 1024
